name: script-copy

on:
  push:
    branches:
      - main
    paths:
      - 'common/*/*'

jobs:
  script-copy:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Copy script files
      shell: bash
      run: >
        for language in java nodejs dotnet python; do
          for service in functions run; do
            for app in hello-http hello-gcs hello-auditlog hello-pubsub; do
              cp common/$app/*.sh $language/$service/$app/scripts
            done
          done
        done

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply script-copy workflow changes
